level1 = ["WWWWWWWWWWWWWWWWWWWWW",
          "W P        W  W     W",
          "W          W  W     W",
          "W          W  W  E  W",
          "W    E     W  W     W",
          "W          W  W     W",
          "W          W  W     W",
          "W          W  W     W",
          "W               E   W",
          "W                   W",
          "W  E                W",
          "W                   W",
          "WWWWWWWWWWWWWWWWWWWWW"]

level2 = ["WWWWWWWWWWWWWWWW",
          "W              W",
          "W              W",
          "W      P       W",
          "W              W",
          "W              W",
          "W              W",
          "WWWWWWWWWWWWWWWW"]
