level1 = ["WWWWWWWWWWWWWWWWWWWWW",
          "W          W  W     W",
          "W          W  W     W",
          "W          W  W  E  W",
          "W    E      W  W    W",
          "W          W  W     W",
          "W          W  W     W",
          "W          W  W     W",
          "W               E   W",
          "W                   W",
          "W  E                W",
          "W                   W",
          "WWWWWWWWWWWWWWWWWWWWW"]